### ISSUE TITLE
Weird window re-size when scene changes

### ISSUE THREAD

**Issue by Ghosts** [doughepi/JavaFX_Login_Dialog#2]
When scenes change from login, to register, then back to login, for some reason the stage size is changed, and what looks like bottom margins.

Seems to only happen to the login scene, still can't find a fix or what is causing it.

**Comment by Ghosts** [comment]
To recreate, run the program twice and on one instance go to register then cancel, and compare with the second window to see the difference.

**Comment by doughepi** [comment]
Fixed. It had to do with setting screen size programmatically and in fxml.
